sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - rm -rf ./node_modules/
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - mongodb
